blank_issues_enabled: false
contact_links:
  - name: Arsentic Community
    url: https://arsentic.net/discord/
    about: Please ask and answer questions here.
  - name: Official Arsentic Support
    url: https://l.arsentic.net/contact
    about: If you would like direct support, please contact us here. Note: you may need to login with a forum account.
